version: '3.7'

services:

  db:
    image: postgres
    container_name: four_player_chess_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: four_player_chess
