spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/four_player_chess
    username: admin
    password: admin
    initialization-mode: always

jwt:
  secret-key: BDKdSNVjQX60q8nRK2RGVI2IIIXuq1j+/quqX0InBbI=
  expiration-time-hours: 8
